baseurl = "https://wizardly-ritchie-d4e42c.netlify.com/"
relativeurls = true
languageCode = "en-us"
title = "Bookdown"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "render_post"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Archive"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Log in"
    url = "/connect/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
[[menu.main]]
    name = "Github"
    url = "https://github.com/rstudio/bookdown"
    weight = 6

[params]
    description = "Write HTML, PDF, ePub, and Kindle books with R Markdown"
    footer = "&copy; [RStudio, Inc.](https://www.rstudio.com) 2016 -- 2018"
